Revert "zuma: Remove vendor/lineage device framework matrix inclusion"
Causing this error:
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.lineage.health.IChargingControl/default (@2)
    vendor.lineage.health.IFastCharge/default (@2)
    vendor.lineage.powershare.IPowerShare/default (@1)
    vendor.lineage.touch.IGloveMode/default (@1)
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 8.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 8 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success
INCOMPATIBLE

This reverts commit e8fafa6d78aa76e4b7037555b2e1229a4c7fd891.

Signed-off-by: Iverz <asterixiverz@gmail.com>